### ISSUE TITLE
Existing Sphinx tutorials

### ISSUE THREAD

**Issue by ericholscher** [pydanny/restructuredtext#1]
http://matplotlib.org/sampledoc/ is a pretty decent one. Geared towards matplotlib

https://pythonhosted.org/an_example_pypi_project/sphinx.html is more of a reference

http://codeandchaos.wordpress.com/2012/07/30/sphinx-autodoc-tutorial-for-dummies/ is an autodoc tutorial

**Comment by luzfcb** [comment]
http://rest-sphinx-memo.readthedocs.org/

**Comment by ericholscher** [comment]
Also:
